apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feedspine

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-api.yaml
  - service-api.yaml

images:
  - name: feedspine-api
    newTag: latest
