apiVersion: v1
kind: Service
metadata:
  name: feedspine-api
  namespace: feedspine
  labels:
    app.kubernetes.io/name: feedspine-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: feedspine
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: feedspine-api
