apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feedspine-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: feedspine-api

configMapGenerator:
  - name: feedspine-config
    behavior: merge
    literals:
      - FEEDSPINE_LOG_LEVEL=DEBUG
      - FEEDSPINE_API_RELOAD=true
